### ISSUE TITLE
Not working when virtuoso is started in silent mode

### ISSUE THREAD

**Issue by yegier** [unihd-cag/skillbridge#177]
Skillbridge is not working when virtuoso is started with -nograph option. I think this behaviour is related to the ipcBeginProcess. It uses stdin to comunicate, and in silent mode it's not activated. Any chance to update it to ipcSkillProcess?

**Comment by nielsbuwen** [comment]
Hi,

sorry for the late response. We did some testing and were able to reproduce the issue. At the moment we hesitate to replace `ipcBeginProcess` with `ipcSkillProcess`, because it may introduce some subtle changes.

However the [direct mode](https://unihd-cag.github.io/skillbridge/usage/quickstart.html?highlight=pyrunscript#direct-mode-without-a-server) still works with the `-nograph` option.

In the future we will experiment with `ipcSkillProcess` and hide that behavior behind a flag. Maybe `pyStartServer ?nograph t`.

Greetings,
Niels and Tobias

**Comment by yegier** [comment]
Great, thanks for the response, actually it was really fast. I remember it didn't work with direct mode. But I will try again. Let me know when the feature is ready. It's really helpful. 
Thanks!
