### ISSUE TITLE
PYTHON: python: symbol lookup error: python: undefined symbol: _Py_LegacyLocaleDetected

### ISSUE THREAD

**Issue by MastellaM** [unihd-cag/skillbridge#201]
While running the script with Cadence I encountered this error after i enter pyStartServer. 

Cadence is running in the terminal with the source venv and the load has been correctly prompted.
What are we doing wrong? Could you please help us figuring out the problem?

Thank you very much and congratulations for the nice job!
Michele

**Comment by nielsbuwen** [comment]
This is a problem we observed in the past. We don't know the exact cause. It seems that python cannot start in certain environments.

We can't fix the actual cause, because it is a python problem.

There is a workaround however: Start the skillbridge server with `pyStartServer ?python "LD_LIBRARY_PATH= python"`.

Copy the command exactly like that. It clears the LD_LIBRARY_PATH environment variable before running python.
