### ISSUE TITLE
[SUPPORT] defining output path for Spectre Simulation Results

### ISSUE THREAD

**Issue by PaulKokhanov1** [unihd-cag/skillbridge#222]
Hello, I was wondering how to use skillbridge to define an output path for the virtuoso spectre simulation results. Currently it seems that the outputs are place in the same directory as my design reference except it is creating a new "distributed" folder and placing the netlist and psf results in this folder. I am unsure why it is creating the "distributed" folder, i'm not sure if this is a feature within virtuoso or whether skillbridge implements this. Ideally I would like to be able to define my simulation output path. Would this be done via cdslib? If so, using python how can I define where the script should look for the cdslib script? Thanks
![image](https://github.com/unihd-cag/skillbridge/assets/69466838/885e1ab6-738b-48a3-b196-1c0e0cf34def)
![image](https://github.com/unihd-cag/skillbridge/assets/69466838/a9ea96f8-e3f8-4fe6-8b37-21fab64ce174)

**Comment by TM90** [comment]
Hello,

Skillbridge is only a thin layout to do type translation and interfacing between skill and python.

To read and change the psf directory paths I would recommend to take a look into the Virtuoso ADE SKILL Reference.
We cannot link cadence documentaiton directly since it is proprietary, so you will need a Cadence Support Account.

I.e. 
``` python
# Skill method:
axlGetResultsLocation(...)
# skillbridge access:
ws.axl.get_results_location(...)
...
```

Hope this helps.

Best regards

Tobias

**Comment by TM90** [comment]
I will close the issue for now If you have additional questions feel free to reopen the issue or open a new one.

Best regards
Tobias
